baseURL = 'https://corvin.tech'
languageCode = 'en-us'
title = 'Corvin.Tech'
disbleKinds = ["taxonomy", "term"]

[menu]

[[menu.main]]
name = 'Talks'
pageRef = '/talks'
weight = 10

[[menu.main]]
name = 'Projects'
pageRef = '/projects'
weight = 20

[params]
hero-subtitles = [
  "Cloud Native",
  "Public Speaker",
  "Podcast Host",
  "University Lecturer",
  "Lego Builder",
  "Taskmaster Enthusiast"
]


[[params.social]]
icon = "fa-brands fa-linkedin"
url = "https://www.linkedin.com/in/corvin-schapöhler/"

[[params.social]]
icon = "fa-brands fa-github"
url = "https://github.com/Etone"

[[params.social]]
icon = "fa-brands fa-codepen"
url = "https://codepen.io/Etone"

[[params.social]]
icon = "fa-regular fa-envelope"
url = "mailto:co.schapoehler@gmail.com"
